translate_dict = {
    'marginAsset': '保证金币种',
    'marginBalance': '保证金余额',
    'pair': '标的交易对',
    'liquidationPrice': '参考强平价格',
    'cumBase': '成交额(标的数量)',
    'baseQty': '成交额(标的数量)',
    'price': '成交价',
    'executedQty': '成交量(张数)',
    'qty': '成交量(张数)',
    'positionSide': '持仓方向',
    'positionAmt': '持仓数量',
    'maintMargin': '持仓维持保证金',
    'unRealizedProfit': '持仓未实现盈亏',
    'stopPrice': '触发价',
    'origType': '触发前订单类型',
    'markPrice': '当前标记价格',
    'leverage': '当前杠杆倍数',
    'maxQty': '当前杠杆倍数允许的数量上限(标的数量)',
    'positionInitialMargin': '当前所需持仓起始保证金(按最新标标记价格)',
    'openOrderInitialMargin': '当前所需挂单起始保证金(按最新标标记价格)',
    'initialMargin': '当前所需起始保证金(按最新标标记价格)',
    'orderId': '订单ID',
    'type': '订单类型',
    'time': '订单时间',
    'status': '订单状态',
    'priceRate': '跟踪止损回调比例',
    'activatePrice': '跟踪止损激活价格',
    'updateTime': '更新时间',
    'id': '交易ID',
    'symbol': '交易对',
    'reduceOnly': '仅减仓',
    'entryPrice': '开仓均价',
    'availableBalance': '可用下单余额',
    'crossWalletBalance': '可用于全仓的账户余额',
    'side': '买卖方向',
    'avgPrice': '平均成交价',
    'crossUnPnl': '全仓持仓未实现盈亏',
    'realizedPnl': '实现盈亏',
    'priceProtect': '是否开启条件单触发保护',
    'maker': '是否是挂单方',
    'buyer': '是否是买方',
    'isolated': '是否是逐仓模式',
    'closePosition': '是否条件全平仓',
    'commission': '手续费',
    'commissionAsset': '手续费单位',
    'workingType': '条件价格触发类型',
    'clientOrderId': '用户自定义的订单号',
    'timeInForce': '有效方法',
    'origQty': '原始委托数量',
    'accountAlias': '账户唯一识别码',
    'balance': '账户余额',
    'walletBalance': '账户余额',
    'isolatedMargin': '逐仓保证金',
    'marginType': '逐仓模式或全仓模式',
    'asset': '资产',
    'withdrawAvailable': '最大可提款金额',
    'maxWithdrawAmount': '最大可提款金额',
    'isAutoAddMargin': '是否自动补充保证金',
    'cumQty': '累计数量',
    'unrealizedProfit': '未实现盈亏',
    'fills': '成交状态',
    'transactTime': '创建时间',
    'free': '可用币数',
    'locked': '冻结币数',
    'total_assets': '总币数',
    'usd_profit': '币本位合约美元价值盈亏',
}
future_trade_type_dict = {
    'cfuture': '币本位合约',
    'ufuture': 'U本位合约'
}
all_trade_type_dict = {
    'spot': '现货',
    'cfuture': '币本位合约',
    'ufuture': 'U本位合约'
}
api_dict = {
    'main': {
            'apiKey': 'ZcVo562JplzdaRRuTbS8PK760r7hGouocKXFi1MjZ56SslMMBqPcPgTFbjvT8Uvi',
            'secret': '6bi9D9Z8rlQUQmjhdw2iv1Mbm9CdXJA1PPuksyZOysQchKL346arHDfs042TemZr',
    },
     'son2': {
        'email': 'ppherry2_virtual@rw2vcdbsnoemail.com',
        'apiKey': "mYpuRg1IsYCBO52k9KMvLHEx7hUQcMpMKrLyrXuILPsVAP7ZKaNkDTWXIaiTuLMU",
        'secret': "u89HSIXXEx3BbItro2RJFBuXI4ZZ5zmYxM36HGINWuD3ZP4ayy8y7uXFEMSfbOvM",
    },
    'son3': {
        'email': 'ppherry3_virtual@91z0byq6noemail.com',
        'apiKey': "uYWLRAPf8iXYDGfOzm5wR6w35uvn6PQWONzxZpe46FUDKLCQrZo3C5lK7HqchyIQ",
        'secret': "fDVklkFaCL36TR1ryjpaR4jZanDfbVwRpW545QUdFJvD1BIXrIPbGpKsABq0mhDa",
    },
    'son1': {
        'email': 'ppherry1_virtual@7gctieg8noemail.com',
        'apiKey': "A3sgiz5hLZ2vGn3uYMm43pFzrrkSCsXR2cPTmZ801MG20Bz91Bve8UuxI6iPLPLj",
        'secret': "OhLkUu99HDKqOhujQEqDvp0Yqi049z5qGe3RqaapGQfWEo91VoR6w5xwd4Tpq2GC",
    },
    'son5': {
        'email': 'ppherry5_virtual@jt9n2acvnoemail.com',
        'apiKey': "DS2xZ14YdEVLkNUTkMcEpWdimbQsr7Ra4brNpyant5Y6iTpS9HKwPXhl6ry6m8i1",
        'secret': "0qZGXK4vmMA8bLm5mgTh17mdavIpZuMfHGt84rYY5uUOxMGVIEQUxTfkSU41IoYn",
    },
    'son4': {
        'email': 'ppherry4_virtual@3qh68epqnoemail.com',
        'apiKey': "DT00t10taGyGwvTKEEmfIxRmUzsrXzlcJLDypFGukl4NUAZxZalWCnHgwOiHg706",
        'secret': "OXLmFhHtq9Af5wgSe3KCOCSgnPD4wivCMJZVBGGhqKVJFE7cyEBqHmxmMSfyeYnk",
    },
    'son12': {
          'email': 'ppherry12_virtual@9phr5pwxnoemail.com',
          'apiKey': "6YDauSlZ1Vin5jBa4QUpEO0v0MuxdAIw9WyKd1G8N16ze8Ehj1LfwpAjclRDJUxQ",
          'secret': "YbydnvFHt1NaL9Vhj0FAVypUhU42Q5cetsOHjFuDLvtWRba7SbBWc5UAeVvl2f0r",
    },
}
